# Generated by Django 5.1.3 on 2024-11-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='article_pdfs/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('contributor', 'Contributor'), ('free', 'Free'), ('admin', 'Admin')], default='free', max_length=20),
        ),
    ]
