# Generated by Django 5.1.3 on 2024-11-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_pdf_file_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='coverimage',
            field=models.ImageField(blank=True, null=True, upload_to='editions/'),
        ),
    ]
