# Generated by Django 5.1.3 on 2024-11-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_edition_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
