# Generated by Django 5.1.3 on 2024-11-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contributor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='edition_pdfs/'),
        ),
    ]
